const translations: Array<[string, string]> = [
  ["Dimitris Galatsanos | IT Systems Engineer", "Δημήτρης Γαλατσάνος | Μηχανικός Συστημάτων Πληροφορικής"],
  ["Skip to content", "Μετάβαση στο περιεχόμενο"],
  ["Primary navigation", "Κύρια πλοήγηση"],
  ["Dimitris Galatsanos home", "Αρχική σελίδα Δημήτρη Γαλατσάνου"],
  ["> About<", "> Σχετικά<"],
  ["> Experience<", "> Εμπειρία<"],
  ["> Projects<", "> Έργα<"],
  ["> Skills<", "> Δεξιότητες<"],
  ["> Blog<", "> Blog<"],
  ["> Contact<", "> Επικοινωνία<"],
  ["Download CV", "Λήψη CV"],
  ["Open navigation", "Άνοιγμα πλοήγησης"],
  ["Close navigation", "Κλείσιμο πλοήγησης"],
  ["IT systems, infrastructure and automation", "Συστήματα IT, υποδομές και αυτοματισμοί"],
  ["Reliable infrastructure. Practical automation. Useful products.", "Υποδομές με αξιοπιστία. Αυτοματισμοί με ουσία."],
  ["IT Systems Engineer with more than 20 years of technology experience, combining hands-on infrastructure operations, monitoring, incident response and software development in business-critical environments.", "Μηχανικός Συστημάτων Πληροφορικής με περισσότερα από 20 χρόνια εμπειρίας στην τεχνολογία, συνδυάζοντας πρακτική διαχείριση υποδομών, παρακολούθηση συστημάτων, απόκριση σε συμβάντα και ανάπτυξη λογισμικού σε επιχειρησιακά κρίσιμα περιβάλλοντα."],
  ["Explore projects", "Δείτε τα έργα"],
  ["Contact me", "Επικοινωνήστε μαζί μου"],
  ["IT Operations", "Λειτουργίες IT"],
  ["reliability · ownership · delivery", "αξιοπιστία · υπευθυνότητα · παράδοση"],
  ["reliability · ownership · delivery", "σταθερότητα · έλεγχος · εξέλιξη"],
  ["Windows Server, Active Directory, Microsoft 365, Entra ID", "Windows Server · AD · M365 · Entra"],
  ["VLANs, switching, Wi-Fi, VoIP, LAN and WAN", "VLAN · Switching · Wi-Fi · VoIP · WAN"],
  ["Zabbix, PingOS, alerting and service visibility", "Zabbix · PingOS · Alerts"],
  ["PowerShell, Python, Power Automate and APIs", "PowerShell · Python · Power Automate"],
  ["Flask, React, SQLite, PWA and custom CMS platforms", "Flask · React · SQLite · PWA"],
  ["alerting and service visibility", "ειδοποιήσεις και ορατότητα υπηρεσιών"],
  ["custom CMS platforms", "προσαρμοσμένες πλατφόρμες CMS"],
  ["systems mindset loaded", "νοοτροπία συστημάτων ενεργή"],
  ["operational ownership enabled", "επιχειρησιακή υπευθυνότητα ενεργή"],
  ["automation and product thinking connected", "αυτοματισμοί και product thinking συνδεδεμένα"],
  ["[A] What I do", "[A] Τι κάνω"],
  ["Three disciplines, one operational mindset.", "Υποδομές, αυτοματισμοί, λογισμικό."],
  ["I work across infrastructure, automation and software because the most useful solutions often sit between those areas. The goal is always the same, reduce friction, improve visibility and keep services dependable.", "Εργάζομαι σε υποδομές, αυτοματισμούς και λογισμικό, επειδή οι πιο χρήσιμες λύσεις βρίσκονται συχνά ανάμεσα σε αυτούς τους τομείς. Ο στόχος παραμένει ο ίδιος: λιγότερη τριβή, καλύτερη ορατότητα και αξιόπιστες υπηρεσίες."],
  ["01 / OPERATE", "01 / ΛΕΙΤΟΥΡΓΙΑ"],
  ["Keep critical services stable.", "Διατηρώ σταθερές τις κρίσιμες υπηρεσίες."],
  ["Own incidents from detection to restoration across endpoints, identity, switching, wireless, telephony, printers and business applications.", "Αναλαμβάνω τα συμβάντα από τον εντοπισμό έως την πλήρη αποκατάσταση, σε endpoints, ταυτότητες, switching, ασύρματα δίκτυα, τηλεφωνία, εκτυπωτές και επιχειρησιακές εφαρμογές."],
  ["Service health", "Υγεία υπηρεσιών"],
  ["live operational view", "ζωντανή επιχειρησιακή εικόνα"],
  ["Identity and access", "Ταυτότητα και πρόσβαση"],
  ["Network and wireless", "Δίκτυο και Wi-Fi"],
  ["Guest-facing systems", "Συστήματα επισκεπτών"],
  ["Printing and telephony", "Εκτυπώσεις και τηλεφωνία"],
  ["HEALTHY", "ΟΜΑΛΗ ΛΕΙΤΟΥΡΓΙΑ"],
  ["02 / AUTOMATE", "02 / ΑΥΤΟΜΑΤΙΣΜΟΙ"],
  ["Turn repetitive work into workflows.", "Μετατρέπω τις επαναλαμβανόμενες εργασίες σε ροές."],
  ["Use PowerShell, Python, monitoring and notification tools to replace manual checks with repeatable and observable processes.", "Χρησιμοποιώ PowerShell, Python, monitoring και εργαλεία ειδοποιήσεων για να αντικαθιστώ τους χειροκίνητους ελέγχους με επαναλήψιμες και παρατηρήσιμες διαδικασίες."],
  ["Automation path", "Ροή αυτοματισμού"],
  ["detect to action", "από τον εντοπισμό στην ενέργεια"],
  ["Observe", "Παρατήρηση"],
  ["service checks", "έλεγχοι υπηρεσιών"],
  ["Decide", "Απόφαση"],
  ["PowerShell and Python logic", "Λογική PowerShell και Python"],
  ["Notify", "Ειδοποίηση"],
  ["Teams, email and reports", "Teams, email και αναφορές"],
  ["03 / BUILD", "03 / ΑΝΑΠΤΥΞΗ"],
  ["Create practical software products.", "Δημιουργώ πρακτικά προϊόντα λογισμικού."],
  ["Translate real operational needs into maintainable applications, from desktop monitoring tools to hospitality platforms and custom publishing systems.", "Μετατρέπω πραγματικές επιχειρησιακές ανάγκες σε συντηρήσιμες εφαρμογές, από εργαλεία παρακολούθησης desktop έως πλατφόρμες φιλοξενίας και προσαρμοσμένα συστήματα δημοσίευσης."],
  ["Product stack", "Τεχνολογικό stack"],
  ["idea to operation", "από την ιδέα στη λειτουργία"],
  ["responsive UI and PWA", "responsive UI και PWA"],
  ["business logic", "επιχειρησιακή λογική"],
  ["audit trails", "ίχνη ελέγχου"],
  ["Deployments, monitoring, backups and support", "Deployments, monitoring, αντίγραφα ασφαλείας και υποστήριξη"],
  ["Operational ownership with engineering depth.", "Τεχνική ευθύνη στην πράξη."],
  ["My work combines hands-on infrastructure support, incident leadership, vendor coordination, automation and technical documentation in environments where downtime has immediate business impact.", "Η εργασία μου συνδυάζει πρακτική υποστήριξη υποδομών, διαχείριση συμβάντων, συντονισμό προμηθευτών, αυτοματισμούς και τεχνική τεκμηρίωση σε περιβάλλοντα όπου η διακοπή λειτουργίας έχει άμεσο επιχειρηματικό αντίκτυπο."],
  ["JAN 2024", "ΙΑΝ 2024"], ["MAR 2023", "ΜΑΡ 2023"], ["JAN 2019", "ΙΑΝ 2019"],
  ["TO PRESENT", "ΕΩΣ ΣΗΜΕΡΑ"], ["TO DEC 2023", "ΕΩΣ ΔΕΚ 2023"],
  ["IT Manager", "Υπεύθυνος Πληροφορικής"],
  ["IT Support Specialist", "Ειδικός Υποστήριξης Πληροφορικής"],
  ["Founder, Editor and Platform Administrator", "Ιδρυτής, Αρχισυντάκτης και Διαχειριστής Πλατφόρμας"],
  ["Lead day-to-day IT operations and infrastructure support in a high-availability hospitality environment, covering business-critical and guest-facing technology services.", "Ηγούμαι της καθημερινής λειτουργίας IT και της υποστήριξης υποδομών σε περιβάλλον φιλοξενίας υψηλής διαθεσιμότητας, καλύπτοντας επιχειρησιακά κρίσιμες υπηρεσίες και τεχνολογίες επισκεπτών."],
  ["Administer Windows Server, Microsoft 365, identities, endpoints, printers, telephony, network devices and operational applications.", "Διαχειρίζομαι Windows Server, Microsoft 365, ταυτότητες, endpoints, εκτυπωτές, τηλεφωνία, δικτυακές συσκευές και επιχειρησιακές εφαρμογές."],
  ["Perform root-cause analysis across VLANs, switching, Aruba wireless infrastructure, VoIP, WAN and ISP connectivity, property systems and third-party services.", "Πραγματοποιώ ανάλυση βασικής αιτίας σε VLANs, switching, ασύρματες υποδομές Aruba, VoIP, συνδέσεις WAN και ISP, property systems και υπηρεσίες τρίτων."],
  ["Develop PowerShell and Python automations for monitoring, notifications, recurring checks and support workflows.", "Αναπτύσσω αυτοματισμούς PowerShell και Python για monitoring, ειδοποιήσεις, επαναλαμβανόμενους ελέγχους και ροές υποστήριξης."],
  ["Supported IT readiness and opening operations for Ikos Kissamos across infrastructure, network, endpoints, telephony, printing and applications.", "Υποστήριξα την ετοιμότητα IT και την έναρξη λειτουργίας του Ikos Kissamos σε υποδομές, δίκτυο, endpoints, τηλεφωνία, εκτυπώσεις και εφαρμογές."],
  ["Provided onsite and remote support for Windows endpoints, Microsoft 365, user access, printers, telephony, connectivity and line-of-business applications.", "Παρείχα επιτόπια και απομακρυσμένη υποστήριξη για Windows endpoints, Microsoft 365, πρόσβαση χρηστών, εκτυπωτές, τηλεφωνία, συνδεσιμότητα και επιχειρησιακές εφαρμογές."],
  ["Resolved escalated Wi-Fi, switching, VLAN, VoIP and peripheral incidents, coordinating external providers when required.", "Επίλυσα κλιμακωμένα συμβάντα Wi-Fi, switching, VLAN, VoIP και περιφερειακών, συντονίζοντας εξωτερικούς συνεργάτες όπου απαιτούνταν."],
  ["Documented repeatable fixes and troubleshooting procedures to improve consistency and reduce restoration time.", "Τεκμηρίωσα επαναλήψιμες λύσεις και διαδικασίες troubleshooting για μεγαλύτερη συνέπεια και μικρότερο χρόνο αποκατάστασης."],
  ["Worked directly with operational teams to translate business impact into clear technical actions.", "Συνεργάστηκα άμεσα με επιχειρησιακές ομάδες, μετατρέποντας τον επιχειρηματικό αντίκτυπο σε σαφείς τεχνικές ενέργειες."],
  ["Own the editorial, technical and operational lifecycle of an independent Greek gaming publication, including contributor coordination, publishing workflows and continuous platform development.", "Έχω την ευθύνη του συντακτικού, τεχνικού και επιχειρησιακού κύκλου ζωής ενός ανεξάρτητου ελληνικού gaming μέσου, από τον συντονισμό συνεργατών και τις ροές δημοσίευσης έως τη συνεχή ανάπτυξη της πλατφόρμας."],
  ["Administer a custom React frontend and custom CMS with PWA functionality.", "Διαχειρίζομαι custom React frontend και προσαρμοσμένο CMS με λειτουργίες PWA."],
  ["Coordinate deployments, contributor access, content operations, issue resolution and feature planning.", "Συντονίζω deployments, πρόσβαση συνεργατών, λειτουργίες περιεχομένου, επίλυση ζητημάτων και σχεδιασμό λειτουργιών."],
  ["Combine product ownership with editorial leadership and community development.", "Συνδυάζω product ownership, συντακτική ηγεσία και ανάπτυξη κοινότητας."],
  ["Professional snapshot", "Επαγγελματική εικόνα"],
  ["years in technology", "χρόνια στην τεχνολογία"],
  ["operational environments", "επιχειρησιακά περιβάλλοντα"],
  ["major independent products", "σημαντικά ανεξάρτητα προϊόντα"],
  ["working languages", "γλώσσες εργασίας"],
  ["Infrastructure scope", "Πεδίο υποδομών"],
  ["Products grounded in real operational needs.", "Λογισμικό για πραγματικές ανάγκες."],
  ["Προϊόντα grounded in real operational needs.", "Λογισμικό για πραγματικές ανάγκες."],
  ["Each project started from a practical problem. The result is software designed around reliability, usability, maintainability and the realities of day-to-day operations.", "Κάθε έργο ξεκίνησε από ένα πρακτικό πρόβλημα. Το αποτέλεσμα είναι λογισμικό σχεδιασμένο για αξιοπιστία, χρηστικότητα, συντηρησιμότητα και τις πραγματικές ανάγκες της καθημερινής λειτουργίας."],
  ["01 / FLAGSHIP PRODUCT", "01 / ΚΥΡΙΟ ΠΡΟΪΟΝ"],
  ["Private hospitality platform", "Ιδιωτική πλατφόρμα εστίασης"],
  ["Hospitality ordering and table operations", "Παραγγελιοληψία και διαχείριση τραπεζιών"],
  ["A full-stack Flask application built to manage restaurant tables, reservations, users, orders, products, VAT, reporting and network printing from one operational interface.", "Μια full-stack εφαρμογή Flask για τη διαχείριση τραπεζιών, κρατήσεων, χρηστών, παραγγελιών, προϊόντων, ΦΠΑ, αναφορών και δικτυακών εκτυπώσεων από ένα ενιαίο επιχειρησιακό περιβάλλον."],
  ["Implements PIN-based users and roles, configurable sessions, table status, reservations, product management, order history, payments and audit logging.", "Υλοποιεί χρήστες και ρόλους με PIN, ρυθμιζόμενα sessions, κατάσταση τραπεζιών, κρατήσεις, διαχείριση προϊόντων, ιστορικό παραγγελιών, πληρωμές και audit logging."],
  ["Routes order items to the correct ESC/POS network printer by category, checks printer availability and stores failed jobs in persistent retry queues.", "Δρομολογεί τα είδη παραγγελίας στον σωστό δικτυακό εκτυπωτή ESC/POS ανά κατηγορία, ελέγχει τη διαθεσιμότητα και αποθηκεύει τις αποτυχημένες εργασίες σε μόνιμες ουρές επανάληψης."],
  ["Uses SQLite for operational and audit data, Excel imports for catalogue maintenance, scheduled background jobs, backups, restore safeguards and PWA support.", "Χρησιμοποιεί SQLite για λειτουργικά δεδομένα και audit, εισαγωγές Excel για συντήρηση καταλόγου, προγραμματισμένες εργασίες, αντίγραφα ασφαλείας, ασφαλή επαναφορά και υποστήριξη PWA."],
  ["Includes MAC-bound encrypted licensing built with Fernet for controlled application deployment.", "Περιλαμβάνει κρυπτογραφημένη αδειοδότηση δεσμευμένη σε MAC, υλοποιημένη με Fernet για ελεγχόμενη διάθεση της εφαρμογής."],
  ["View source on GitHub", "Προβολή κώδικα στο GitHub"],
  ["Operational architecture", "Επιχειρησιακή αρχιτεκτονική"],
  ["application workflow", "ροή εφαρμογής"],
  ["Front of house", "Χώρος εξυπηρέτησης"],
  ["Tables and reservations", "Τραπέζια και κρατήσεις"],
  ["Capacity, spaces, availability and daily bookings", "Χωρητικότητα, χώροι, διαθεσιμότητα και ημερήσιες κρατήσεις"],
  ["Orders and payments", "Παραγγελίες και πληρωμές"],
  ["Products, quantities, notes, status and history", "Προϊόντα, ποσότητες, σημειώσεις, κατάσταση και ιστορικό"],
  ["Users and sessions", "Χρήστες και sessions"],
  ["PIN access, roles and inactivity timeout", "Πρόσβαση με PIN, ρόλοι και timeout αδράνειας"],
  ["Application core", "Πυρήνας εφαρμογής"],
  ["Flask service layer", "Επίπεδο υπηρεσιών Flask"],
  ["Routes, validation, business rules and JSON actions", "Routes, validation, επιχειρησιακοί κανόνες και ενέργειες JSON"],
  ["Operational database", "Λειτουργική βάση δεδομένων"],
  ["Audit and recovery", "Έλεγχος και ανάκτηση"],
  ["Deletion logs, backups, exports and restore safeguards", "Αρχεία διαγραφών, backups, exports και ασφαλής επαναφορά"],
  ["Kitchen and services", "Κουζίνα και υπηρεσίες"],
  ["Category routing", "Δρομολόγηση ανά κατηγορία"],
  ["Send each item to the correct network printer", "Αποστολή κάθε είδους στον σωστό δικτυακό εκτυπωτή"],
  ["Persistent retry queues", "Μόνιμες ουρές επανάληψης"],
  ["Store unavailable print jobs and recover automatically", "Αποθήκευση μη διαθέσιμων εκτυπώσεων και αυτόματη ανάκτηση"],
  ["Background scheduler", "Χρονοπρογραμματιστής παρασκηνίου"],
  ["Pending jobs, receipts and recurring checks", "Εκκρεμείς εργασίες, αποδείξεις και επαναλαμβανόμενοι έλεγχοι"],
  ["02 / MONITORING", "02 / ΠΑΡΑΚΟΛΟΥΘΗΣΗ"],
  ["Desktop application", "Εφαρμογή desktop"],
  ["Network and device status monitoring", "Παρακολούθηση κατάστασης δικτύου και συσκευών"],
  ["A Python and PyQt5 desktop application created for practical infrastructure monitoring and operational reporting.", "Εφαρμογή desktop σε Python και PyQt5 για πρακτική παρακολούθηση υποδομών και επιχειρησιακές αναφορές."],
  ["Imports multi-sheet Excel inventories and creates a monitoring tab for every device category.", "Εισάγει αρχεία Excel πολλαπλών φύλλων και δημιουργεί καρτέλα παρακολούθησης για κάθε κατηγορία συσκευών."],
  ["Runs concurrent checks with QThread and ping3, showing availability, latency, packet loss and timestamps.", "Εκτελεί παράλληλους ελέγχους με QThread και ping3, εμφανίζοντας διαθεσιμότητα, latency, packet loss και timestamps."],
  ["Provides configurable polling, searchable status history, manual checks, dark mode and CSV, Excel or PDF exports.", "Παρέχει ρυθμιζόμενο polling, αναζητήσιμο ιστορικό κατάστασης, χειροκίνητους ελέγχους, dark mode και εξαγωγές CSV, Excel ή PDF."],
  ["Monitoring workflow", "Ροή παρακολούθησης"],
  ["four stages", "τέσσερα στάδια"],
  ["Load", "Φόρτωση"], ["Check", "Έλεγχος"], ["Track", "Καταγραφή"], ["Report", "Αναφορά"],
  ["Excel device inventory", "Απογραφή συσκευών Excel"],
  ["Concurrent ping workers", "Παράλληλοι ping workers"],
  ["Status, latency and logs", "Κατάσταση, latency και logs"],
  ["03 / EDTECH", "03 / ΕΚΠΑΙΔΕΥΤΙΚΗ ΤΕΧΝΟΛΟΓΙΑ"],
  ["Live product", "Ενεργό προϊόν"],
  ["Interactive learning and contextual AI tutoring", "Διαδραστική μάθηση και AI καθοδήγηση με context"],
  ["A bilingual learning platform designed around hands-on programming practice, immediate feedback and personalized support.", "Μια δίγλωσση πλατφόρμα μάθησης σχεδιασμένη γύρω από την πρακτική εξάσκηση στον προγραμματισμό, την άμεση ανατροφοδότηση και την εξατομικευμένη υποστήριξη."],
  ["Provides browser-based coding so learners can write and run code without local setup.", "Παρέχει προγραμματισμό μέσα από τον browser, ώστε οι εκπαιδευόμενοι να γράφουν και να εκτελούν κώδικα χωρίς τοπική εγκατάσταση."],
  ["Uses an AI tutor for explanations, hints, debugging guidance and feedback during exercises.", "Χρησιμοποιεί AI tutor για επεξηγήσεις, υποδείξεις, καθοδήγηση debugging και ανατροφοδότηση κατά τις ασκήσεις."],
  ["Supports personal notes, PDFs and learning material as context, with a mobile-optimized interface.", "Υποστηρίζει προσωπικές σημειώσεις, PDF και εκπαιδευτικό υλικό ως context, με interface βελτιστοποιημένο για κινητά."],
  ["Learning workspace", "Χώρος μάθησης"],
  ["code and tutor", "κώδικας και tutor"],
  ["AI tutor", "AI εκπαιδευτής"],
  ["Run in browser", "Εκτέλεση στον browser"],
  ["Immediate feedback", "Άμεση ανατροφοδότηση"],
  ["Personal context", "Προσωπικό context"],
  ["04 / MEDIA PLATFORM", "04 / ΠΛΑΤΦΟΡΜΑ ΜΕΣΩΝ"],
  ["2019 to present", "2019 έως σήμερα"],
  ["An independent Greek gaming publication developed as a complete editorial and technology product, not as a standard WordPress installation.", "Ένα ανεξάρτητο ελληνικό gaming μέσο, ανεπτυγμένο ως ολοκληρωμένο συντακτικό και τεχνολογικό προϊόν και όχι ως τυπική εγκατάσταση WordPress."],
  ["Publishes news, reviews, previews, Shorts and long-form Respawn Stories, plus Essentials, Editorial and Respawn+ content.", "Δημοσιεύει νέα, reviews, previews, Shorts και εκτενή Respawn Stories, μαζί με περιεχόμενο Essentials, Editorial και Respawn+."],
  ["Runs on a custom React frontend and custom CMS with PWA delivery, contributor access and tailored publishing workflows.", "Λειτουργεί με custom React frontend και CMS, PWA διάθεση, πρόσβαση συνεργατών και προσαρμοσμένες ροές δημοσίευσης."],
  ["Own the full operational lifecycle across editorial direction, content administration, deployments, issue resolution, feature planning and user-experience improvements.", "Αναλαμβάνω ολόκληρο τον επιχειρησιακό κύκλο ζωής: συντακτική κατεύθυνση, διαχείριση περιεχομένου, deployments, επίλυση ζητημάτων, σχεδιασμό λειτουργιών και βελτιώσεις εμπειρίας χρήστη."],
  ["Editorial product lifecycle", "Κύκλος ζωής συντακτικού προϊόντος"],
  ["plan to delivery", "από τον σχεδιασμό στην παράδοση"],
  ["Plan", "Σχεδιασμός"], ["Produce", "Παραγωγή"], ["Manage", "Διαχείριση"], ["Deliver", "Παράδοση"],
  ["A complete stack for systems, networks, automation and software.", "Τεχνογνωσία από άκρο σε άκρο."],
  ["The strongest part of my profile is the combination. I can diagnose infrastructure, coordinate incidents, automate recurring work and build software that directly supports operations.", "Το ισχυρότερο στοιχείο του προφίλ μου είναι ο συνδυασμός. Μπορώ να διαγνώσω υποδομές, να συντονίσω συμβάντα, να αυτοματοποιήσω επαναλαμβανόμενες εργασίες και να αναπτύξω λογισμικό που υποστηρίζει άμεσα τη λειτουργία."],
  ["Microsoft ecosystem", "Οικοσύστημα Microsoft"],
  ["Networking and connectivity", "Δικτύωση και συνδεσιμότητα"],
  ["Monitoring and automation", "Παρακολούθηση και αυτοματισμοί"],
  ["Infrastructure operations", "Λειτουργία υποδομών"],
  ["Software and data", "Λογισμικό και δεδομένα"],
  ["Leadership and delivery", "Ηγεσία και παράδοση"],
  ["[Q] Credentials", "[Q] Προσόντα"],
  ["Education, certifications and professional foundation.", "Σπουδές και πιστοποιήσεις."],
  ["Education", "Εκπαίδευση"],
  ["Hellenic Open University", "Ελληνικό Ανοικτό Πανεπιστήμιο"],
  ["Undergraduate studies in Computer Engineering, in progress since October 2022.", "Προπτυχιακές σπουδές στη Μηχανική Υπολογιστών, σε εξέλιξη από τον Οκτώβριο του 2022."],
  ["IT Applications Specialist — IEK Chalkidiki, Vocational Training Certification (2002)", "Ειδικός Εφαρμογών Πληροφορικής — Ι.Ε.Κ. Χαλκιδικής, Βεβαίωση Επαγγελματικής Κατάρτισης (2002)"],
  ["Computer Systems and Applications Support — TEE Polygyros, IT and Computer Networks (2001)", "Υποστήριξη Συστημάτων και Εφαρμογών Υπολογιστών — Τ.Ε.Ε. Πολυγύρου, Τομέας Πληροφορικής–Δικτύων Η/Υ (2001)"],
  ["Microsoft certifications", "Πιστοποιήσεις Microsoft"],
  ["Additional development", "Πρόσθετη κατάρτιση"],
  ["Python and continuous learning", "Python και συνεχής μάθηση"],
  ["Hands-on development across Python, Flask, React and infrastructure automation", "Πρακτική ανάπτυξη εφαρμογών με Python, Flask και React, καθώς και αυτοματισμών υποδομών"],
  ["Greek native speaker, comfortable communicating in English", "Ελληνικά μητρική γλώσσα, άνετη επικοινωνία στα Αγγλικά"],
  ["Let’s build systems that work better.", "Ας βελτιώσουμε τα συστήματά σας."],
  ["Available for IT systems, infrastructure operations, automation and technical product roles where reliability, ownership and practical engineering matter.", "Διαθέσιμος για ρόλους σε συστήματα IT, λειτουργία υποδομών, αυτοματισμούς και τεχνικά προϊόντα, όπου η αξιοπιστία, η υπευθυνότητα και η πρακτική μηχανική έχουν σημασία."],
  ["Open profile", "Άνοιγμα προφίλ"],
  ["Curriculum Vitae", "Βιογραφικό σημείωμα"],
  ["Download PDF", "Λήψη PDF"],
  ["IT Systems Engineer · Automation · Infrastructure Operations", "Μηχανικός Συστημάτων IT · Αυτοματισμοί · Λειτουργία Υποδομών"],
  ["[A] About", "[A] Σχετικά"], ["[E] Experience", "[E] Εμπειρία"],
  ["[P] Projects", "[P] Έργα"], ["[S] Skills", "[S] Δεξιότητες"], ["[B] Blog", "[B] Blog"], ["[C] Contact", "[C] Επικοινωνία"],
  ["Frontend", "Frontend"], ["Backend", "Backend"], ["Data", "Δεδομένα"], ["Operations", "Λειτουργία"],
  ["Stories", "Ιστορίες"], ["Long-form retrospectives", "Εκτενή αφιερώματα"],
  ["Editorial", "Αρθρογραφία"], ["Opinion and analysis", "Άποψη και ανάλυση"],
  ["News", "Νέα"], ["Daily publishing workflow", "Καθημερινή ροή δημοσίευσης"],
  ["Curated recommendations", "Επιλεγμένες προτάσεις"],
  ["Content, access and contributors", "Περιεχόμενο, πρόσβαση και συνεργάτες"],
  ["Identity", "Πρόσβαση"],
  ["Networking", "Δίκτυα"],
  ["Monitoring", "Monitoring"],
  ["Automation", "Automation"],
  ["Products", "Εφαρμογές"],
  ["Member-focused publishing", "Δημοσιεύσεις για μέλη"],
  ["Responsive web delivery", "Responsive διαδικτυακή διάθεση"],
  ["Continuous releases", "Συνεχείς εκδόσεις"],
  ["Features, fixes and UX improvements", "Λειτουργίες, διορθώσεις και βελτιώσεις UX"],
  ["User, group, permission and account lifecycle administration.", "Διαχείριση χρηστών, ομάδων, δικαιωμάτων και κύκλου ζωής λογαριασμών."],
  ["Tenant operations", "Λειτουργία tenant"],
  ["Licensing, access, endpoint support and security fundamentals.", "Αδειοδότηση, πρόσβαση, υποστήριξη endpoints και βασικές αρχές ασφάλειας."],
  ["Service troubleshooting", "Αντιμετώπιση προβλημάτων υπηρεσιών"],
  ["Practical diagnosis across Windows and Microsoft cloud environments.", "Πρακτική διάγνωση σε περιβάλλοντα Windows και Microsoft cloud."],
  ["VLAN and port diagnosis", "Διάγνωση VLAN και θυρών"],
  ["Access, trunk and incorrect VLAN assignment troubleshooting.", "Αντιμετώπιση προβλημάτων access, trunk και λανθασμένης ανάθεσης VLAN."],
  ["Wireless operations", "Λειτουργία ασύρματων δικτύων"],
  ["Client issues, access points, service degradation and monitoring.", "Ζητήματα clients, access points, υποβάθμιση υπηρεσιών και monitoring."],
  ["Provider coordination", "Συντονισμός παρόχων"],
  ["WAN, ISP outages, escalation and continuity support.", "Βλάβες WAN και ISP, κλιμάκωση και υποστήριξη επιχειρησιακής συνέχειας."],
  ["Proactive visibility", "Προληπτική ορατότητα"],
  ["Availability checks, alert interpretation and operational monitoring.", "Έλεγχοι διαθεσιμότητας, ερμηνεία ειδοποιήσεων και επιχειρησιακό monitoring."],
  ["Workflow automation", "Αυτοματοποίηση ροών"],
  ["Recurring checks, notifications, reporting and support tasks.", "Επαναλαμβανόμενοι έλεγχοι, ειδοποιήσεις, αναφορές και εργασίες υποστήριξης."],
  ["Incident response", "Απόκριση σε συμβάντα"],
  ["Detection, root-cause analysis, communication and restoration.", "Εντοπισμός, ανάλυση βασικής αιτίας, επικοινωνία και αποκατάσταση."],
  ["Business continuity", "Επιχειρησιακή συνέχεια"],
  ["Support for business-critical and guest-facing technology services.", "Υποστήριξη επιχειρησιακά κρίσιμων τεχνολογικών υπηρεσιών και υπηρεσιών επισκεπτών."],
  ["Operational ownership", "Επιχειρησιακή υπευθυνότητα"],
  ["Issues managed from first report through full restoration.", "Διαχείριση ζητημάτων από την πρώτη αναφορά έως την πλήρη αποκατάσταση."],
  ["Standards and handover", "Πρότυπα και παράδοση"],
  ["Repeatable procedures, technical notes and knowledge sharing.", "Επαναλήψιμες διαδικασίες, τεχνικές σημειώσεις και διαμοιρασμός γνώσης."],
  ["Full-stack products", "Full-stack προϊόντα"],
  ["Responsive interfaces, backend logic and operational workflows.", "Responsive interfaces, backend λογική και επιχειρησιακές ροές."],
  ["Relational data", "Σχεσιακά δεδομένα"],
  ["Schema design, transactions, reporting, audit data and backups.", "Σχεδιασμός schema, transactions, αναφορές, δεδομένα audit και backups."],
  ["Background services", "Υπηρεσίες παρασκηνίου"],
  ["Threaded tasks, schedulers, retry queues and network printing.", "Threaded εργασίες, schedulers, ουρές επανάληψης και δικτυακές εκτυπώσεις."],
  ["Clear communication", "Σαφής επικοινωνία"],
  ["Translate technical incidents into business impact and next steps.", "Μετατρέπω τα τεχνικά συμβάντα σε επιχειρηματικό αντίκτυπο και σαφή επόμενα βήματα."],
  ["Cross-team coordination", "Συντονισμός μεταξύ ομάδων"],
  ["Work with central teams, departments, providers and external partners.", "Συνεργασία με κεντρικές ομάδες, τμήματα, παρόχους και εξωτερικούς συνεργάτες."],
  ["Practical improvement", "Πρακτική βελτίωση"],
  ["Identify recurring friction and build repeatable solutions.", "Εντοπίζω επαναλαμβανόμενα προβλήματα και δημιουργώ επαναλήψιμες λύσεις."],
  ["05 / PUBLISHED PYTHON SOFTWARE", "05 / ΔΗΜΟΣΙΕΥΜΕΝΟ ΛΟΓΙΣΜΙΚΟ PYTHON"],
  ["Independent releases", "Ανεξάρτητες κυκλοφορίες"],
  ["Published Python Applications", "Δημοσιευμένες εφαρμογές Python"],
  ["Software delivery through interactive desktop products", "Παράδοση λογισμικού μέσα από διαδραστικά desktop προϊόντα"],
  ["Two Windows applications engineered with Python and Pygame, released publicly through itch.io and maintained through versioned updates.", "Δύο εφαρμογές Windows αναπτυγμένες με Python και Pygame, δημοσιευμένες στο itch.io και συντηρημένες μέσα από εκδόσεις και ενημερώσεις."],
  ["Designed real-time event loops, input handling, state transitions, scoring, progression, audio and local persistence.", "Σχεδίασα real-time event loops, χειρισμό input, μεταβάσεις κατάστασης, scoring, progression, ήχο και τοπική αποθήκευση."],
  ["Implemented online leaderboards, offline-safe score handling, unlockable content and responsive user feedback.", "Υλοποίησα online leaderboards, ασφαλή διαχείριση score χωρίς σύνδεση, unlockable περιεχόμενο και άμεσο UI feedback."],
  ["Managed packaging, public releases, changelogs, user feedback and iterative bug fixes.", "Διαχειρίστηκα packaging, δημόσιες κυκλοφορίες, changelogs, σχόλια χρηστών και επαναληπτικές διορθώσεις."],
  ["View BlockMaster on itch.io", "Προβολή BlockMaster στο itch.io"],
  ["View Flappy Wings on itch.io", "Προβολή Flappy Wings στο itch.io"],
  ["Python release workflow", "Ροή κυκλοφορίας Python"],
  ["build to maintenance", "από την ανάπτυξη στη συντήρηση"],
  ["Real-time puzzle system with progression, score persistence, global ranking and versioned releases.", "Real-time puzzle σύστημα με progression, αποθήκευση score, παγκόσμια κατάταξη και εκδόσεις."],
  ["Interactive application with physics, dynamic conditions, unlockable content and local/global scores.", "Διαδραστική εφαρμογή με physics, δυναμικές συνθήκες, unlockable περιεχόμενο και local/global scores."],
  ["01 / Build", "01 / Ανάπτυξη"],
  ["Logic, state and interface", "Logic, state και interface"],
  ["02 / Package", "02 / Packaging"],
  ["Windows distribution", "Διανομή για Windows"],
  ["03 / Release", "03 / Κυκλοφορία"],
  ["Public version delivery", "Δημόσια διάθεση έκδοσης"],
  ["04 / Iterate", "04 / Βελτίωση"],
  ["Feedback, fixes and updates", "Feedback, διορθώσεις και updates"],
  ["Why return a value instead of printing inside the function?", "Γιατί να επιστρέψουμε μια τιμή αντί να κάνουμε print μέσα στη συνάρτηση;"],
  ["Returning keeps the function reusable. You can print, test or store the result later.", "Η επιστροφή τιμής διατηρεί τη συνάρτηση επαναχρησιμοποιήσιμη. Μπορείτε αργότερα να εκτυπώσετε, να ελέγξετε ή να αποθηκεύσετε το αποτέλεσμα."],
  ["[PLAY] Interactive system check", "[PLAY] Διαδραστικός έλεγχος συστήματος"],
  ["Keep the network alive. Jump over outages, collect clean signals and stay online for as long as you can.", "Κράτησε το δίκτυο ζωντανό. Πήδα πάνω από βλάβες, μάζεψε καθαρά σήματα και μείνε online όσο περισσότερο μπορείς."],
  ["Network online", "Δίκτυο online"],
  ["Score", "Σκορ"], ["Best", "Ρεκόρ"],
  ["Keep it online", "Κράτησέ το online"],
  ["Jump over outages. Collect signal packets.", "Πήδα πάνω από βλάβες. Μάζεψε πακέτα σήματος."],
  ["Start run", "Έναρξη"], ["Jump", "Πήδημα"], ["Pause", "Παύση"], ["Mobile", "Κινητό"],
  ["Runs locally in your browser · No tracking · Best score stays on this device", "Τρέχει τοπικά στον browser · Χωρίς tracking · Το ρεκόρ μένει σε αυτή τη συσκευή"],
];

export function translatePortfolioToGreek(source: string) {
  let result = source;
  for (const [english, greek] of translations) result = result.replaceAll(english, greek);
  return result
    .replace('<html lang="en">', '<html lang="el">')
    .replaceAll('href="favicon.ico"', 'href="../favicon.ico"')
    .replaceAll('href="favicon.svg"', 'href="../favicon.svg"')
    .replaceAll('href="favicon-64.png"', 'href="../favicon-64.png"')
    .replaceAll('href="Dimitris_Galatsanos_CV.pdf"', 'href="../Dimitris_Galatsanos_CV_GR.pdf"')
    .replace('href="gr/" data-language="el" aria-label="View portfolio in Greek">GR</a>', 'href="../" data-language="en" aria-label="Προβολή portfolio στα Αγγλικά">EN</a>')
    .replace('href="gr/" data-language="el">[GR] Ελληνικά</a>', 'href="../" data-language="en">[EN] English</a>');
}
